### ISSUE TITLE
[1.15.2] Problems with setting skull texture

### ISSUE THREAD

**Issue by Thatsmusic99** [brainsynder-Dev/BSLib#1]
Leaving this here for future reference as this one bug has officially given me a headache that not even aspirin can solve.

On 1.15.2 (tested on both Paper and ordinary Spigot), skull textures cannot be set. It seems to be an upstream problem with the NMS itself, as when attempting to set the profile, something seems to be causing this error to be thrown (when trying to convert the item to a string for debugging):

```[15:31:21] [Server thread/WARN]: java.lang.NullPointerException
[15:31:21] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.NBTTagCompound.a(SourceFile:441)
[15:31:21] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.NBTTagCompound.write(SourceFile:101)
[15:31:21] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:100)
[15:31:21] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:93)
[15:31:21] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:51)
[15:31:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1281)
[15:31:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:210)
[15:31:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1225)
[15:31:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaItem.toString(CraftMetaItem.java:1374)
[15:31:21] [Server thread/WARN]:        at java.lang.String.valueOf(String.java:2994)
[15:31:21] [Server thread/WARN]:        at java.lang.StringBuilder.append(StringBuilder.java:131)
[15:31:21] [Server thread/WARN]:        at org.bukkit.inventory.ItemStack.toString(ItemStack.java:255)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.internal.bslib.item.ItemBuilder.handleMeta(ItemBuilder.java:306)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.internal.bslib.item.ItemBuilder.setTexture(ItemBuilder.java:226)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.menu.menuItems.Silent.getDefaultItems(Silent.java:38)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.reflection.ReflectionUtil.getMenuItemsJSON(ReflectionUtil.java:113)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.pet.PetType.loadDefaults(PetType.java:65)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.internal.bslib.files.JsonFile.reload(JsonFile.java:44)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.pet.TypeManager.register(TypeManager.java:114)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.pet.TypeManager.<init>(TypeManager.java:23)
[15:31:21] [Server thread/WARN]:        at simplepets.brainsynder.PetCore.onEnable(PetCore.java:85)
[15:31:21] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:31:21] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[15:31:21] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[15:31:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[15:31:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[15:31:21] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[15:31:21] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267)
[15:31:21] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[15:31:21] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
```
During debugging, I found nothing wrong with the skull meta and nothing wrong with the game profile; everything seemed to be set properly. The texture was fully encoded as well.

This bug, strangely, does not occur on 1.16.1 or 1.14.4 either, implying that this could be a problem with 1.15.2.

However, when my plugin - HeadsPlus - uses a similar technique, it is able to load the textures just fine and with no errors, implying that it could also be a BSLib problem.

I've left this open to PR should we not find the cause ourselves.

**Comment by Thatsmusic99** [comment]
Error seems to occur on 1.16.1 too but is able to set the texture fine.

**Comment by Thatsmusic99** [comment]
Confirmed to be an unrelated problem with BSLib and is instead a problem with SimplePets' installation for 1.15.2.
